/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

val scalaMiddleVersion = "2.12"
val scalaVersion = "2.12.19"
val sparkVersion = "3.4.3" // Set your desired Spark version



plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // Add the custom Kakao NLP repository
//    maven {
//        url = uri("https://repo.daumkakao.io/content/groups/kakao-nlp-group")
//    }
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:$scalaVersion")

    // This dependency is used by the application.
    implementation(libs.guava)

    // https://mvnrepository.com/artifact/org.apache.spark/spark-core
    implementation("org.apache.spark:spark-core_$scalaMiddleVersion:$sparkVersion")
    implementation("org.apache.spark:spark-sql_$scalaMiddleVersion:$sparkVersion")
    implementation("org.apache.spark:spark-hive_$scalaMiddleVersion:$sparkVersion")
    implementation("org.apache.spark:spark-mllib_$scalaMiddleVersion:$sparkVersion")

    // Add the new Kakao dependency
//    implementation("com.kakao:dha:2.9.4")
//    implementation(files("/Users/whishaw/wss/dha/build/lib/dha.jar"))


    // Use Scalatest for testing our library
    testImplementation(libs.junit)
    testImplementation(libs.scalatest.v2.v13)
    testImplementation(libs.junit.v4.v13.v2.v13)

    // Need scala-xml at test runtime
    testRuntimeOnly(libs.scala.xml.v2.v13)
}

// Apply a specific Java toolchain to ease working on different environments.
//java {
//    toolchain {
//        languageVersion.set(JavaLanguageVersion.of(11))
//    }
//}

application {
    // Define the main class for the application.
    mainClass.set("crawl_scala.App")
}
